# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf085151b6cdc058ed31d9fc9528a9b9549cb2ca1e5c0b624e8fc1488f73e374b391bec434732bc4481aa6381237ac9ea7441254577d6cbb93f6f7467b3d6628

test:
  secret_key_base: 2e0ebfb794a20c67c2baf0525d62905f5ff2613004b241cee77fd419ad37fcd0cca3c14faef5d864b333f72f96441392da7d125a736e59430dd84099ee3b53d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
